config/routes.rb
Rails.application.routes.draw do

  get 'thank_you/index'

  resources :participants, only: [:new, :create, :update] do
    collection do
      get :edit_feedback, as: :edit_feedback
      patch :accept_consent, as: :accept_consent
    end
  end

  resources :apis, only: [:show, :index] do
    resources :tasks, only: [:show] do
      resources :answers, only: [:create]
    end
  end

  root 'apis#index'

  get 'thank_you' => 'thank_you#index', as: :thank_you

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  METHODS = %W{GET POST PATCH DELETE PUT HEAD}
  scope :default, -> {where default: true}
  belongs_to :task
  has_one :response, dependent: :destroy
  validates :method, inclusion: {in: METHODS, allow_nil: true}
  belongs_to :participant

  def submit!
    api_response = RestClient::Request.execute(method: method.downcase.to_sym,
      url: url,
      payload: request_body,
      headers: request_headers_hash)
  rescue RestClient::Exception => exception
    api_response = exception.response
  ensure
    create_response!(headers: api_response.headers.to_json, body: api_response.body, status_code: api_response.code)
  end

  def url
    URI.join(task.api.root, path).to_s
  end

  def request_headers_hash
    return {} if request_headers.blank?

    request_headers.lines.reduce({}) do |headers, line|
      header_name, header_value = line.split(":").map(&:chomp)
      headers[header_name] = header_value if header_name
      headers
    end
  end

end

app/models/api.rb
class Api < ActiveRecord::Base
  has_many :tasks, dependent: :destroy

  module DocVersion
    ORIGINAL = :original
    FORKED = :forked
  end

  def practice_task
    tasks.practice.first || tasks.first
  end

  def doc_url_for(doc_version)
#    sym_doc_version = doc_version.to_sym
#    if sym_doc_version == DocVersion::ORIGINAL
      doc_url
#    else
#      forked_doc_url
#    end

  end
end

app/models/participant.rb
class Participant < ActiveRecord::Base

  has_many :answers, dependent: :destroy

  before_create :select_doc_version

  def self.experience_ratings
    (0..10).to_a
  end

  def select_doc_version
    if nth_partipant?(4)
      self.doc_version = Api::DocVersion::FORKED
    else
      self.doc_version = Api::DocVersion::ORIGINAL
    end
  end

  def nth_partipant?(every_n)
    total_participants = self.class.count
    total_participants % every_n == 0
  end

end

app/models/response.rb
class Response < ActiveRecord::Base
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :api
  has_many :answers, dependent: :destroy

  scope :practice, -> { where(practice: true)}

  def default_or_new_answer
    answers.default.first.try(:dup) || answers.build
  end

  def next
    all_tasks.where('tasks.id > ?', id).first
  end

  def all_tasks
    api.tasks.order(:id)
  end

  def index
    all_tasks.index(self)
  end

  def previous_task
    all_tasks.where('tasks.id < ?', id).last
  end

  def self.completed_by(participant)
    joins(:answers).where(answers: {participant_id: participant.id}).distinct
  end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  skip_before_action :setup_session, only: :index

  def create
    @task = Task.find(params[:task_id])
    answer_params = params.require(:answer).permit(:path, :method, :request_headers, :request_body)

    @answer = @task.answers.create!(answer_params.merge(participant_id: participant.id))
    @answer.submit!
    redirect_to api_task_path(@task.api_id, @task, answer_id: @answer.id), notice: 'API call performed. See the response below.'
  end

  def index
    task_id = params[:task_id]
    doc_version = params[:doc_version]
    file = Tempfile.open("task-#{task_id}-data.md")
    task = Task.find(task_id)
    file.puts "# Task:  #{task.title}. #{task.description}\n"

    Participant.where(doc_version: doc_version).order(:id).each do |participant|
       file.puts "\n### Participant: #{participant.code_name} using #{participant.doc_version} API documentation\n"
       task.answers.where(participant_id: participant.id).find_each.with_index do |answer, index|
         file.puts "\n#### Answer #{index + 1}"
         file.puts ""
         file.puts ""
         file.puts ""
         file.puts ""
         file.puts ""
         file.puts ""
         file.puts ""
         file.puts ""
         file.puts ""
         file.puts ""
         file.puts ""
         file.puts ""

         file.puts "- Time: ```#{answer.created_at.strftime("%H:%M:%S")}```\n"
         file.puts "- Method: ```#{answer.method}```\n"
         file.puts "- PATH: ```#{answer.path.strip}```\n"
         file.puts "- Request Headers: ```#{answer.request_headers.strip}```\n" if answer.request_headers.present?
         file.puts "- Request Body: ```#{answer.request_body.strip}```\n" if answer.request_body.present?
         file.puts "- Response Code: ```#{answer.response.status_code}```\n" if answer.response.present?
         file.puts "- Response Body: ```#{answer.response.body.truncate(400).strip}```\n" if answer.response.present?
      end
    end

    file.close
    send_file file.path, type: 'text/markdown; charset=UTF-8', filename: "task-#{task_id}-#{doc_version}-data.md"
  end

end

app/controllers/apis_controller.rb
class ApisController < ApplicationController

  def index
    @api = Api.first
    redirect_to api_path(@api)
  end

  def show
    @api = Api.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :setup_session

  helper_method :participant

  def participant
    @participant
  end

  private
  def setup_session
    if session[:participant_id]
      @participant = Participant.find(session[:participant_id])
    else
      redirect_to new_participant_path
    end
  end

end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  skip_before_action :setup_session, only: [:new, :create, :index]


  def index
    doc_version = params[:doc_version]
    file = Tempfile.open("participants-#{doc_version}-data.md")

    Participant.where(doc_version: doc_version).order(:new_code_name).each do |participant|
      file.puts "## #{participant.new_code_name}"
      file.puts ""
      file.puts "1. **Rating**: #{participant.experience_rating} / 10"
      file.puts "2. **Feedback**: #{participant.feedback}"
      file.puts ""
    end
    file.close
    send_file file.path, type: 'text/markdown; charset=UTF-8', filename: "participants-#{doc_version}-data.md"

  end

  def new
    @participant = Participant.new
  end

  def create
    participant_params = params.require(:participant).permit(:name, :company, :years_of_industry_experience, :years_of_experience_with_rest_apis)
    participant = Participant.create!(participant_params)
    session[:participant_id] = participant.id
    redirect_to root_path
  end

  def edit_feedback
    if @participant.answers.exists?
      @api = @participant.answers.last.task.api
    end
  end

  def update
    participant_params = params.require(:participant).permit(:experience_rating, :feedback)
    participant.update_attributes!(participant_params)
    redirect_to thank_you_path
  end

  def accept_consent
    participant_params = params.require(:participant).permit(:grant_company_name_use)
    participant.update_attributes!(participant_params)
    api = Api.first
    redirect_to api_task_path(api, api.tasks.first)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task

  def show
    if params[:answer_id]
      @answer = @task.answers.where(participant_id: participant.id).find(params[:answer_id])
    else
      @answer = @task.default_or_new_answer
    end
  end



  private
  def set_task
    @task = Task.find(params[:id])
  end
end

app/controllers/thank_you_controller.rb
class ThankYouController < ApplicationController
  def index
    @finished = true
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/apis_helper.rb
module ApisHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/thank_you_helper.rb
module ThankYouHelper
end

app/views/answers/create.html.erb
<h1>Answers#create</h1>
<p>Find me in app/views/answers/create.html.erb</p>

app/views/apis/show.html.erb
<%= content_for :page_title do%>
Consent
<% end %>

<%= form_for participant, url: accept_consent_participants_path do |participant_form|%>

<div>
  <small>
    The University of Calgary Conjoint Faculties Research Ethics Board has approved this research study. Participation is completely voluntary, and confidential. You are free to discontinue participation at any time during the study.
  </small>

  <h3>Purpose of the Study</h3>
  <small>
    You’ll be taking part in the study to improve the state of REST API documentation. Specifically, we’re trying to identify and measure, if any, the productivity difference of REST API client developers when they are given API documentation with or without usage examples.
  </small>

  <h3>What Will I Be Asked To Do?</h3>

  <small>
    You’ll be asked to perform 6 API tasks using an open-source REST API and its accompanying documentation. This web-based system will record the API calls you’ll make for us to later analyze, and potentially publish the results. You’ll be requested to provide a satisfaction rating and a free-form feedback about your experience using the API to end the study.
  </small>

  <h3>What Type of Personal Information Will Be Collected?</h3>
  <small>
    We request for your name and comany name for us to identify the participants. Only the researchers will have access to your name. Published material will remove the real name with a surrogate code name. The relationship between the code name and the company name will not be published. The following options are for you to consider if you decide to take part in this research.
  </small>

  <h3>Are there Risks or Benefits if I Participate?</h3>
  <small>
    You provide us with data to analyze and improve the state of REST API documentation for software
    engineers including yourself. The risks are none to minimal.
  </small>

  <h3>What Happens to the Information I Provide?</h3>

  <small>
    Only the researchers have access to the collected identifiable data. It’s saved on a password protected cloud database hosted and secured the cloud platform provider Heroku (https://www.heroku.com/policy/security). Collected data can be removed upon request to the researcher (smsohan@ucalgary.ca) by April 1, 2017. Participation is completely voluntary, and confidential. You are free to discontinue participation at any time. The data will be stored for a maximum of two years on the database, at which time, it will be permanently erased.
  </small>
  <small>
    Your acceptance on this form indicates that 1) you understand to your satisfaction the information provided to you about your participation in this research project, and 2) you agree to participate in the research project.
    In no way does this waive your legal rights nor release the investigators, sponsors, or involved institutions from their legal and professional responsibilities. You are free to withdraw from this research project at any time. You should feel free to ask for clarification or new information throughout your participation.
  </small>
</small>
<p>
  <%= participant_form.check_box :grant_company_name_use %>
  <strong>
    <%= participant_form.label :grant_company_name_use, 'I grant permission to have my company’s name used without directly relating to my responses' %>
  </strong>
</p>


<%= participant_form.submit "I accept. Let's get started" %>  <%= link_to "Not interested", thank_you_path %>

</div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RestApiExplorer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if browser.device.mobile? %>
  <div class="callout yellow">

    To participate you please use a computer instead of a phone since the tasks require you to browse some API documentation and use an on-line API call editor that works best on larger displays.
  </div>
  <% end %>

  <h1 class="banner">Live API Explorer</h1>

  <% if participant %>
  <div class="participant-name">
    Thank you <strong><%= participant.name %></strong> for participating in this study.
    <% unless @finished %>
    You can <%= link_to 'finish', edit_feedback_participants_path %> anytime.
    <% end %>
  </div>
  <% end %>


  <h2 class="page-title"><%= yield :page_title %></h2>

  <%= yield %>


  <div class="footer">
    <small>
      If you have any concerns about the way you’ve been treated as a participant, please contact Research Ethics Administrators, Research Services Office, University of Calgary at (403) 220-6289/220-4283; email cfreb@ucalgary.ca. A copy of this consent form has been given to you to keep for your records and reference. The investigator has kept a copy of the consent form.

    </small>
  </div>

</body>
</html>

app/views/participants/edit_feedback.html.erb
<%= form_for participant do |participant_form|%>

  <fieldset>
    <legend>Feedback</legend>


    <dl>
      <dt><%= participant_form.label :experience_rating, "Rate your experience of performing the API tasks using the <strong>#{@api ? @api.name : ''}</strong> documentation (10 being the best possible)".html_safe %> </dt>
      <dd><%= participant_form.select :experience_rating, Participant.experience_ratings, prompt:  'Select one' %></dd>
      <dt><%= participant_form.label :feedback, 'Share your thoughts about the reasoning behind the above rating' %> </dt>
      <dd><%= participant_form.text_area :feedback, rows: 5, cols: 80 %></dd>
    </dl>

    <%= submit_tag 'Submit' %>

  </fieldset>


<% end %>

app/views/participants/new.html.erb
<%= form_for @participant, html: {class: 'half-width'} do |participant_form|%>

  <fieldset>
    <legend>Profile</legend>

    <dl>
      <dt><%= participant_form.label :name %></dt>
      <dd><%= participant_form.text_field :name, size: 50, placeholder: 'John...', required: true %></dd>
      <dt><%= participant_form.label :company %></dt>
      <dd><%= participant_form.text_field :company, size: 50, placeholder: 'Company...', required: true  %></dd>
      <dt><%= participant_form.label :years_of_industry_experience %></dt>
      <dd><%= participant_form.number_field :years_of_industry_experience, required: true %></dd>
      <dt><%= participant_form.label :years_of_experience_with_rest_apis, "Years of experience with REST APIs" %></dt>
      <dd><%= participant_form.number_field :years_of_experience_with_rest_apis, required: true %></dd>

      <dd></dd>
    </dl>


    <%= submit_tag 'Next' %>
  </fieldset>


<% end %>

app/views/tasks/show.html.erb
<p class="notice"><%= notice %></p>

<div class="callout info">
  You can make multiple API calls for each task until you think the current task is complete or you want to skip to the next step.
</div>


<% if @task.practice %>
  <h3 class="callout yellow">This is a Practice Task. Click Submit to see the API Response.</h3>
<% end %>

<dl>
  <dt>Task (<%= @task.api.tasks.completed_by(participant).count %>/<%= @task.api.tasks.count %>)</dt>
  <dd>
    <p>
      <strong><%= @task.title %>.</strong> <%=auto_link @task.description, html: { target: '_blank' } %>
    </p>
  </dd>
  <dt>API Docs</dt>
  <dd><%=link_to @task.api.doc_url_for(@participant.doc_version), @task.api.doc_url_for(@participant.doc_version), target: '_blank' %></dd>
</dl>

<div class="two-panel">
  <div class="left">
    <%= form_for @answer.dup, url: api_task_answers_path(@task.api, @task) do |answer_form| %>
      <fieldset>
        <legend>API Call Editor</legend>

        <dl>
          <dt><%= answer_form.label :method %></dt>
          <dd class="code-snippet"><%=answer_form.select :method, Answer::METHODS, {prompt: 'Select one'}, required: true %></dd>
        </dl>

        <dl>
          <dt><%= answer_form.label :path, 'Request Path' %></dt>
          <dd class="code-snippet"><%= @task.api.root %><%= answer_form.text_field :path, size: 30, placeholder: 'Request path...', class: 'code-snippet', required: true %></dd>
        </dl>

        <dl>
          <dt><%= answer_form.label :request_headers %></dt>
          <dd><%= answer_form.text_area :request_headers, cols: 30, rows: 5, class: 'code-snippet' , placeholder: 'e.g. x-custom-header: my custom value (one header per row)' %></dd>
        </dl>

        <dl>
          <dt><%= answer_form.label :request_body %></dt>
          <dd><%= answer_form.text_area :request_body, cols: 30, rows: 5, class: 'code-snippet' , placeholder: 'Request body...' %></dd>
        </dl>


        <div class="buttons" >

          <%= submit_tag 'Submit' %>

          <span class="paginator">

            <% if @task.previous_task %>
              <%= link_to 'Previous Task', api_task_path(@task.api, @task.previous_task) %>
            <% end %>

            <% if  @task.next %>
              <%= link_to 'Next Task', api_task_path(@task.api, @task.next) %>
            <% else %>
              <%= link_to 'Finish', edit_feedback_participants_path %>
            <% end %>

          </span>

        </div>

      </fieldset>
    <% end %>

  </div>

  <div class="right">

    <fieldset>
      <legend>API Response</legend>
      <% if @answer.response %>
        <div class="response-data">
          <dl>
            <dt>Response Code</dt>
            <dd><pre class='code-snippet'><%= @answer.response.status_code %></pre></dd>
          </dl>

          <dl>
            <dt>Response Headers</dt>
            <dd>
              <pre class='code-snippet'><%= JSON.pretty_generate JSON.parse(@answer.response.headers) %></pre>
            </dd>
          </dl>

          <dl>
            <dt>Response Body</dt>
            <dd><pre class='code-snippet'><%= JSON.pretty_generate JSON.parse(@answer.response.body) %></pre></dd>
          </dl>
        </div>
      <% else %>
        <p>This section will show you the API response once you submit the form.</p>
      <% end %>
    </fieldset>
  </div>
<div>